### ISSUE TITLE
Suggestion: Add to Racket or Pollen topics

### ISSUE THREAD

**Issue by celtic-coder** [treeman/why_cryptocurrencies#43]
Hi Jonas,

For extra visibility, it might be an idea to include this repo in the following topics:

- [Racket](https://github.com/topics/racket) (1,041  repositories)
- [Pollen](https://github.com/topics/pollen) ( 46 repositories)

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
Hi Jonas,

For extra visibility, it might be an idea to include this repo in the following topics:

- [Racket](https://github.com/topics/racketl) (1,041  repositories)
- [Pollen](https://github.com/topics/pollen) ( 46 repositories)

Kind Regards,
Liam

**Comment by treeman** [comment]
Oh, I didn't know about the topics. I've added it there now.

Thanks!

**Comment by celtic-coder** [comment]
You're welcome! 🙂👍
